use uuid::Uuid;

use crate::enums::{
    ProtocolType, SerialFlowControlMode, SerialParityMode, SerialStopBitsMode,
};
use crate::serial::SerialDefaults;

/// Fully resolved connection profile (`Wormhole.Models.ConnectionProfile`).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ConnectionProfile {
    pub node_id: Uuid,
    pub name: String,
    pub parent_folder_name: Option<String>,
    pub protocol: ProtocolType,
    pub host: String,
    pub port: i32,
    pub username: Option<String>,
    pub credential_id: Option<Uuid>,
    pub is_ephemeral: bool,
    pub use_inline_password: bool,

    pub rdp_domain: Option<String>,
    pub rdp_screen_size: Option<String>,
    pub rdp_full_screen: bool,
    pub rdp_color_depth: i32,
    pub rdp_use_all_monitors: bool,
    pub rdp_audio_mode: i32,
    pub rdp_audio_capture_mode: i32,
    pub rdp_keyboard_hook_mode: i32,
    pub rdp_redirect_clipboard: bool,
    pub rdp_redirect_printers: bool,
    pub rdp_redirect_smart_cards: bool,
    pub rdp_redirect_ports: bool,
    pub rdp_redirect_devices: bool,
    pub rdp_redirect_drives: String,
    pub rdp_connection_speed: i32,
    pub rdp_desktop_background: bool,
    pub rdp_font_smoothing: bool,
    pub rdp_desktop_composition: bool,
    pub rdp_window_drag: bool,
    pub rdp_menu_animation: bool,
    pub rdp_visual_styles: bool,
    pub rdp_bitmap_caching: bool,
    pub rdp_auto_reconnect: bool,
    pub rdp_server_authentication: i32,
    pub rdp_gateway_usage_method: i32,
    pub rdp_gateway_hostname: Option<String>,
    pub rdp_gateway_credential_id: Option<Uuid>,
    pub rdp_gateway_bypass_local: bool,
    pub rdp_gateway_use_same_creds: bool,
    pub rdp_use_external_client: bool,

    pub ssh_key_file_name: Option<String>,
    pub ssh_known_host_fingerprint: Option<String>,
    pub ssh_auto_sudo: bool,

    pub serial_baud_rate: i32,
    pub serial_data_bits: i32,
    pub serial_stop_bits: SerialStopBitsMode,
    pub serial_parity: SerialParityMode,
    pub serial_flow_control: SerialFlowControlMode,

    pub http_ignore_cert_errors: bool,

    pub tunnel_enabled: bool,
    pub tunnel_config_id: Option<Uuid>,
}

impl Default for ConnectionProfile {
    fn default() -> Self {
        Self {
            node_id: Uuid::nil(),
            name: String::new(),
            parent_folder_name: None,
            protocol: ProtocolType::Ssh,
            host: String::new(),
            port: 22,
            username: None,
            credential_id: None,
            is_ephemeral: false,
            use_inline_password: false,
            rdp_domain: None,
            rdp_screen_size: None,
            rdp_full_screen: false,
            rdp_color_depth: 32,
            rdp_use_all_monitors: false,
            rdp_audio_mode: 0,
            rdp_audio_capture_mode: 0,
            rdp_keyboard_hook_mode: 2,
            rdp_redirect_clipboard: true,
            rdp_redirect_printers: false,
            rdp_redirect_smart_cards: false,
            rdp_redirect_ports: false,
            rdp_redirect_devices: false,
            rdp_redirect_drives: String::new(),
            rdp_connection_speed: 7,
            rdp_desktop_background: true,
            rdp_font_smoothing: true,
            rdp_desktop_composition: true,
            rdp_window_drag: true,
            rdp_menu_animation: true,
            rdp_visual_styles: true,
            rdp_bitmap_caching: true,
            rdp_auto_reconnect: true,
            rdp_server_authentication: 2,
            rdp_gateway_usage_method: 0,
            rdp_gateway_hostname: None,
            rdp_gateway_credential_id: None,
            rdp_gateway_bypass_local: true,
            rdp_gateway_use_same_creds: false,
            rdp_use_external_client: false,
            ssh_key_file_name: None,
            ssh_known_host_fingerprint: None,
            ssh_auto_sudo: false,
            serial_baud_rate: SerialDefaults::BAUD_RATE,
            serial_data_bits: SerialDefaults::DATA_BITS,
            serial_stop_bits: SerialDefaults::STOP_BITS,
            serial_parity: SerialDefaults::PARITY,
            serial_flow_control: SerialDefaults::FLOW_CONTROL,
            http_ignore_cert_errors: false,
            tunnel_enabled: false,
            tunnel_config_id: None,
        }
    }
}
